# Generated by Django 3.2 on 2023-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('cantidad_recibida', models.IntegerField(blank=True, default=0, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=50, null=True)),
                ('comprador', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('punto_de_pedido', models.IntegerField(blank=True, default=0, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('exportar_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
