# Generated by Django 3.2 on 2023-08-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='cantidad_recibida',
            new_name='cantidad_comprada',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='cantidad_entregada',
            new_name='cantidad_gastada',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='vendedor',
            new_name='gastado_por',
        ),
        migrations.AddField(
            model_name='stock',
            name='precio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
