# Generated by Django 3.2 on 2023-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagementApp', '0002_auto_20230816_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
