# Generated by Django 3.2 on 2023-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagementApp', '0003_stock_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('Unidad', 'Unidad(es)'), ('Bote', 'Bote(s)'), ('Bandeja', 'Bandeja(s)'), ('Brick', 'Brick(s)'), ('Tableta', 'Tableta(s)'), ('Botella', 'Botella(s)')], max_length=50, null=True),
        ),
    ]
