# Generated by Django 3.2 on 2023-10-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagementApp', '0004_auto_20231007_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockManagementApp.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('Unidad', 'Unidad/es'), ('Bote', 'Bote/s'), ('Bandeja', 'Bandeja/s'), ('Brick', 'Brick/s'), ('Tableta', 'Tableta/s'), ('Botella', 'Botella/s')], max_length=50, null=True),
        ),
    ]
