# Generated by Django 3.2 on 2023-10-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagementApp', '0005_auto_20231007_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='exportar_csv',
        ),
        migrations.AlterField(
            model_name='stock',
            name='categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockManagementApp.categoria'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('Unidad', 'Unidad/es'), ('Bote', 'Bote/s'), ('Bandeja', 'Bandeja/s'), ('Brick', 'Brick/s'), ('Tableta', 'Tableta/s'), ('Botella', 'Botella/s'), ('Lata', 'Lata/s'), ('Tarro', 'Tarro/s'), ('Taza', 'Taza/s'), ('Tubo', 'Tubo/s'), ('Bolsa', 'Bolsa/s')], max_length=50, null=True),
        ),
    ]
